name: ZeusMod
main: fit.seems.mc.zeusmod.ZeusModPlugin
version: 1.3.0
commands:
  zfly:
    description: "sets the fly speed when holding golden boots (default 10)"
    usage: /<command> <speed>
  zwalk:
    description: "sets the walk speed when holding golden boots (default: 20)"
    usage: /<command> <speed>
  zreset:
    description: "resets your speed values"
    usage: /<command>
